/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>

#define BASE_TIM_ADDR      0x40012000UL

#define OFFSET_TIM_ADDR    0x04UL

#define ADDR_TIM           (BASE_TIM_ADDR+OFFSET_TIM_ADDR)

#define BASE_CLK_ADDR      0x40023800UL

#define OFFSET_CLK_ADDR    0x44UL

#define ADDR_CLK           (BASE_CLK_ADDR+OFFSET_CLK_ADDR)

int main(void)
{
	uint32_t *pClkEnbl = (uint32_t*) ADDR_CLK;
	uint32_t *pCtrlDcmi = (uint32_t*) ADDR_TIM;

	*pClkEnbl |= (1 << 8);

    *pCtrlDcmi |= (1 << 8);

    for(;;);
}
